lang: es 
notebook-links: global

project:
  type: book  
  output-dir: docs  
  
# resources: 
  # - clases/ejercicios/005_E001.ipynb
#   title: "Descargar libreta 005_E001"
#   download: true

  
book:
  title: "Proyectos de ciencia de datos con Python"
  # language: es
  # author: Guillermo Barrios
  # version: 0.9.1
  navbar:
    search: True
  sidebar:
    menu: True
    collapse-level: 1
    border: true
    # logo: img/python.png
    right: Construido con [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  repo-url: https://github.com/altamarmx/python-2026-1/
  chapters:
    - index.qmd 
    # - cuadro_honor.qmd 
    # - proyecto_final.qmd
    - clases/001_terminal_python_uv.qmd
    - clases/002_hola_mundo.ipynb
    - clases/003_indentado.ipynb
    - clases/004_variables.ipynb
    - clases/005_nombres_variables.ipynb
    - clases/006_strings_lists.ipynb
    - clases/007_strings_cadenas.ipynb
    - clases/008_list_comprehension.ipynb
    - clases/009_built_in_functions.ipynb
    - clases/010_Operaciones.ipynb
    - clases/011_bloques_control.ipynb
    - clases/012_funciones_tipado.ipynb
    - clases/013_jerarquia.ipynb
    - clases/014_importando_funciones.ipynb
    - clases/015_modificar_funciones.ipynb
    - clases/016_Instalar_paquetes.ipynb
    - clases/016a_ejercicio_clase.qmd
    - clases/cheat_sheet_uv.qmd
    - clases/017_importando_datos.ipynb
    - clases/018_importa_DOS.ipynb
    - clases/019_importa_TRES.ipynb
    - clases/020_importa_XLS.ipynb
    - clases/021_ETL_EDA.ipynb
    - clases/022_parquet.ipynb
    - clases/023_importando_datos.ipynb
    - clases/024_ETL.ipynb
    - clases/025_EDA.ipynb
    - clases/026_importa_exceles.ipynb
    - clases/027_EDA_esolmet.ipynb
    - clases/028_importa_exceles.ipynb
    - clases/029_EDA.ipynb
    - clases/030_amplitud_promedio.ipynb
    - clases/031_importa_exceles.ipynb
    - clases/uv-git-github.qmd
    - clases/032a_heatmap_mensual_diario.ipynb
    - clases/032b_dia_promedio.ipynb
    - clases/033_modificar_dataframe.ipynb
    - clases/034_dia_promedio_dias.ipynb

format:
  html: 
    theme: 
      light: spacelab
      dark: slate
    code-link: true    
    number-sections: true
    number-depth: 1


